### ISSUE TITLE
could not load platform certs

### ISSUE THREAD

**Issue by ysharma1126** [glotlabs/gdrive#112]
FYI, I performed `gdrive account import` on remote for account added locally

thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-rustls-0.23.2/src/config.rs:31:62:
could not load platform certs: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by zabakala** [comment]
Hi @ysharma1126 Did you manage to resolve the issue and if so how? Thx.

**Comment by amandamana** [comment]
thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-rustls-0.23.2/src/config.rs:31:62:
could not load platform certs: Custom { kind: Other, error: Error { code: -25262, message: "The Trust Settings Record was corrupted." } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
